copy styles.css ..\Tai_Chi
copy styles.css ..\Computer_Camp
copy styles.css ..\20th_Anniversary
copy styles.css ..\25th_Anniversary
copy styles.css ..\Calligraphy
copy styles.css ..\Canada_Day
copy styles.css ..\Chess_Competitions
copy styles.css ..\Chinese_New_Year
copy styles.css ..\Chinese_School
copy styles.css ..\Choir
copy styles.css ..\Community_Activities
copy styles.css ..\Cooking_Class
copy styles.css ..\Dance_Class
copy styles.css ..\Display
copy styles.css ..\Flower_Arranging
copy styles.css ..\Fund_Raising
copy styles.css ..\Judo_Class
copy styles.css ..\KiteMaking_Workshop
copy styles.css ..\Member_Activity
copy styles.css ..\Mothers_Day_Recital
copy styles.css ..\Music_Group
copy styles.css ..\Painting
copy styles.css ..\Shadow_Puppets
copy styles.css ..\Speech_Competition
copy styles.css ..\Sports_Day
copy styles.css ..\Summer_Camp
copy styles.css ..\Xmas
copy styles.css ..\Year_End
copy styles.css ..\Youth_Group
